/* eslint-env node */
/* eslint-disable import/no-commonjs */
const NodePolyfillPlugin = require("node-polyfill-webpack-plugin");

const webpack = require("webpack");

const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const HtmlWebpackHarddiskPlugin = require("html-webpack-harddisk-plugin");
const TerserPlugin = require("terser-webpack-plugin");
const WebpackNotifierPlugin = require("webpack-notifier");

const fs = require("fs");

const ASSETS_PATH = __dirname + "/resources/frontend_client/app/assets";
const FONTS_PATH = __dirname + "/resources/frontend_client/app/fonts";
const SRC_PATH = __dirname + "/frontend/src/metabase";
const MINIMAL_SRC_PATH = __dirname + "/frontend/src/minimal";
const LIB_SRC_PATH = __dirname + "/frontend/src/metabase-lib";
const ENTERPRISE_SRC_PATH =
  __dirname + "/enterprise/frontend/src/metabase-enterprise";
const TYPES_SRC_PATH = __dirname + "/frontend/src/metabase-types";
const CLJS_SRC_PATH = __dirname + "/frontend/src/cljs";
const TEST_SUPPORT_PATH = __dirname + "/frontend/test/__support__";
const BUILD_PATH = __dirname + "/resources/frontend_client";

// default WEBPACK_BUNDLE to development
const WEBPACK_BUNDLE = process.env.WEBPACK_BUNDLE || "development";
const devMode = WEBPACK_BUNDLE !== "production";
const useFilesystemCache = process.env.FS_CACHE === "true";
const shouldUseEslint =
  process.env.WEBPACK_BUNDLE !== "production" &&
  process.env.USE_ESLINT === "true";

// Babel:
const BABEL_CONFIG = {
  cacheDirectory: process.env.BABEL_DISABLE_CACHE ? false : ".babel_cache",
};

const CSS_CONFIG = {
  localIdentName: devMode
    ? "[name]__[local]___[hash:base64:5]"
    : "[hash:base64:5]",
  importLoaders: 1,
};

const config = (module.exports = {
  mode: devMode ? "development" : "production",
  context: SRC_PATH,

  // output a bundle for the app JS and a bundle for styles
  // eventually we should have multiple (single file) entry points for various pieces of the app to enable code splitting
  entry: {
    "app-main": "./app-main.js",
    "app-public": "./app-public.js",
    "app-embed": "./app-embed.js",
    styles: "./css/index.css",
  },

  // output to "dist"
  output: {
    path: BUILD_PATH + "/app/dist",
    // NOTE: the filename on disk won't include "?[chunkhash]" but the URL in index.html generated by HtmlWebpackPlugin will:
    filename: "[name].bundle.js?[chunkhash]",
    publicPath: "app/dist/",
  },

  module: {
    rules: [
      {
        test: /\.(tsx?|jsx?)$/,
        exclude: /node_modules|cljs/,
        use: [{ loader: "babel-loader", options: BABEL_CONFIG }],
      },
      ...(shouldUseEslint
        ? [
            {
              test: /\.(tsx?|jsx?)$/,
              exclude: /node_modules|cljs|\.spec\.js/,
              use: [
                {
                  loader: "eslint-loader",
                  options: {
                    rulePaths: [__dirname + "/frontend/lint/eslint-rules"],
                  },
                },
              ],
            },
          ]
        : []),
      {
        test: /\.(eot|woff2?|ttf|svg|png)$/,
        type: "asset/resource",
      },
      {
        test: /\.css$/,
        use: [
          devMode
            ? "style-loader"
            : {
                loader: MiniCssExtractPlugin.loader,
                options: {
                  publicPath: "./",
                },
              },
          { loader: "css-loader", options: CSS_CONFIG },
          { loader: "postcss-loader" },
        ],
      },
    ],
  },
  resolve: {
    extensions: [
      ".webpack.js",
      ".web.js",
      ".js",
      ".jsx",
      ".ts",
      ".tsx",
      ".css",
      ".svg",
    ],
    alias: {
      assets: ASSETS_PATH,
      fonts: FONTS_PATH,
      minimal: MINIMAL_SRC_PATH,
      metabase: SRC_PATH,
      "metabase-lib": LIB_SRC_PATH,
      "metabase-enterprise": ENTERPRISE_SRC_PATH,
      "metabase-types": TYPES_SRC_PATH,
      cljs: CLJS_SRC_PATH,
      __support__: TEST_SUPPORT_PATH,
      style: SRC_PATH + "/css/core/index",
      ace: __dirname + "/node_modules/ace-builds/src-min-noconflict",
      // NOTE @kdoh - 7/24/18
      // icepick 2.x is es6 by defalt, to maintain backwards compatability
      // with ie11 point to the minified version
      icepick: __dirname + "/node_modules/icepick/icepick.min",
      // conditionally load either the EE plugins file or a empty file in the CE code tree
      "ee-plugins":
        process.env.MB_EDITION === "ee"
          ? ENTERPRISE_SRC_PATH + "/plugins"
          : SRC_PATH + "/lib/noop",
    },
  },
  cache: useFilesystemCache
    ? {
        type: "filesystem",
        buildDependencies: {
          // invalidates the cache on configuration change
          config: [__filename],
        },
      }
    : undefined,
  optimization: {
    splitChunks: {
      cacheGroups: {
        vendors: {
          test: /[\\/]node_modules[\\/]/,
          chunks: "all",
          name: "vendor",
        },
      },
    },
  },

  plugins: [
    // Extracts initial CSS into a standard stylesheet that can be loaded in parallel with JavaScript
    // NOTE: the filename on disk won't include "?[chunkhash]" but the URL in index.html generated by HtmlWebpackPlugin will:
    new MiniCssExtractPlugin({
      filename: devMode ? "[name].css" : "[name].css?[contenthash]",
      chunkFilename: devMode ? "[id].css" : "[id].css?[contenthash]",
    }),
    new HtmlWebpackPlugin({
      filename: "../../index.html",
      chunksSortMode: "manual",
      chunks: ["vendor", "styles", "app-main"],
      template: __dirname + "/resources/frontend_client/index_template.html",
      inject: "head",
      // Using default of "defer" creates race-condition when applying whitelabel colors (metabase#18173)
      scriptLoading: "blocking",
      alwaysWriteToDisk: true,
    }),
    new HtmlWebpackPlugin({
      filename: "../../public.html",
      chunksSortMode: "manual",
      chunks: ["vendor", "styles", "app-public"],
      template: __dirname + "/resources/frontend_client/index_template.html",
      inject: "head",
      scriptLoading: "blocking",
      alwaysWriteToDisk: true,
    }),
    new HtmlWebpackPlugin({
      filename: "../../embed.html",
      chunksSortMode: "manual",
      chunks: ["vendor", "styles", "app-embed"],
      template: __dirname + "/resources/frontend_client/index_template.html",
      inject: "head",
      scriptLoading: "blocking",
      alwaysWriteToDisk: true,
    }),
    new HtmlWebpackHarddiskPlugin({
      outputPath: __dirname + "/resources/frontend_client/app/dist",
    }),
    new webpack.BannerPlugin({
      banner:
        "/*\n* This file is subject to the terms and conditions defined in\n * file 'LICENSE.txt', which is part of this source code package.\n */\n",
    }),
    new NodePolyfillPlugin(), // for crypto, among others
    new webpack.EnvironmentPlugin({
      WEBPACK_BUNDLE: "development",
    }),
  ],
});

if (WEBPACK_BUNDLE === "hot") {
  config.target = "web";
  // suffixing with ".hot" allows us to run both `yarn run build-hot` and `yarn run test` or `yarn run test-watch` simultaneously
  config.output.filename = "[name].hot.bundle.js?[contenthash]";

  // point the publicPath (inlined in index.html by HtmlWebpackPlugin) to the hot-reloading server
  config.output.publicPath =
    "http://localhost:8080/" + config.output.publicPath;

  config.module.rules.unshift({
    test: /\.jsx$/,
    // NOTE: our verison of react-hot-loader doesn't play nice with react-dnd's DragLayer, so we exclude files named `*DragLayer.jsx`
    exclude: /node_modules|cljs|DragLayer\.jsx$/,
    use: [
      // NOTE Atte Keinänen 10/19/17: We are currently sticking to an old version of react-hot-loader
      // because newer versions would require us to upgrade to react-router v4 and possibly deal with
      // asynchronous route issues as well. See https://github.com/gaearon/react-hot-loader/issues/249
      { loader: "react-hot-loader/webpack" },
      { loader: "babel-loader", options: BABEL_CONFIG },
    ],
  });

  config.devServer = {
    hot: true,
    headers: {
      "Access-Control-Allow-Origin": "*",
    },
    static: {
      directory: "frontend",
    },
    // tweak stats to make the output in the console more legible
    // TODO - once we update webpack to v4+ we can just use `errors-warnings` preset
    devMiddleware: {
      stats: {
        assets: false,
        cached: false,
        cachedAssets: false,
        chunks: false,
        chunkModules: false,
        chunkOrigins: false,
        modules: false,
        color: true,
        hash: false,
        warnings: true,
        errorDetals: false,
      },
    },
    // if webpack doesn't reload UI after code change in development
    // watchOptions: {
    //     aggregateTimeout: 300,
    //     poll: 1000
    // }
    // if you want to reduce stats noise
    // stats: 'minimal' // values: none, errors-only, minimal, normal, verbose
  };

  config.plugins.unshift(
    new webpack.NoEmitOnErrorsPlugin(),
    new webpack.HotModuleReplacementPlugin(),
  );
}

if (WEBPACK_BUNDLE !== "production") {
  // replace minified files with un-minified versions
  for (const name in config.resolve.alias) {
    const minified = config.resolve.alias[name];
    const unminified = minified.replace(/[.-\/]min\b/g, "");
    if (minified !== unminified && fs.existsSync(unminified)) {
      config.resolve.alias[name] = unminified;
    }
  }

  // by default enable "cheap" source maps for fast re-build speed
  // with BETTER_SOURCE_MAPS we switch to sourcemaps that work with breakpoints and makes stacktraces readable
  config.devtool = process.env.BETTER_SOURCE_MAPS
    ? "inline-source-map"
    : "cheap-module-source-map";

  // helps with source maps
  config.output.devtoolModuleFilenameTemplate = "[absolute-resource-path]";
  config.output.pathinfo = true;

  config.plugins.push(
    new WebpackNotifierPlugin({
      excludeWarnings: true,
      skipFirstNotification: true,
    }),
  );
} else {
  config.plugins.push(
    new TerserPlugin({ parallel: true, test: /\.(tsx?|jsx?)($|\?)/i }),
  );

  config.devtool = "source-map";
}


<div class="react-grid-item DashCard cssTransforms react-resizable-hide react-resizable" style="width: 506px; height: 732px; position: absolute; transform: translate(921px, 0px);"><div class="Card bordered rounded flex flex-column hover-parent hover--visibility"><div class="flex-full overflow-hidden flex flex-column full-height"><div class="p1 flex-no-shrink"><div class="ChartCaptionstyled__ChartCaptionRoot-sc-1vx21pg-0 evEnoJ LegendCaptionstyled__LegendCaptionRoot-sc-1flyvle-0 kQcvpG" data-testid="legend-caption"><div class="fullscreen-normal-text fullscreen-night-text LegendCaptionstyled__LegendLabel-sc-1flyvle-1 frSevv"><div class="" style="overflow: hidden; white-space: nowrap; text-overflow: ellipsis;">Top Vendors</div></div><div class="LegendActionsstyled__LegendActionsRoot-sc-9y9nw4-0 koWbYA"><span class="flex align-center"></span></div></div></div><div class="CardVisualization flex-full flex-basis-none relative flex flex-column"><div class="flex-full relative"><div class="absolute top bottom left right scroll-x scroll-show scroll-show--hover" style="overflow-y: hidden;"><table class="CtorL ipoXK fullscreen-normal-text fullscreen-night-text"><thead><tr><th class="TableInteractive-headerCellData cellData text-brand-hover text-medium"><div class="relative"><svg class="Icon Icon-chevronup Icon__StyledIcon-oj89wd-1 boNzPM" viewBox="0 0 32 32" width="8" height="8" fill="currentcolor" role="img" aria-label="chevronup icon" style="position: absolute; right: 100%; margin-right: 3px;"><path d="M1 20 L16 6 L31 20 L27 24 L16 14 L5 24 z"></path></svg><div class="" style="overflow: hidden; white-space: nowrap; text-overflow: ellipsis;">Logo</div></div></th><th class="TableInteractive-headerCellData cellData text-brand-hover text-medium"><div class="relative"><svg class="Icon Icon-chevronup Icon__StyledIcon-oj89wd-1 boNzPM" viewBox="0 0 32 32" width="8" height="8" fill="currentcolor" role="img" aria-label="chevronup icon" style="position: absolute; right: 100%; margin-right: 3px;"><path d="M1 20 L16 6 L31 20 L27 24 L16 14 L5 24 z"></path></svg><div class="" style="overflow: hidden; white-space: nowrap; text-overflow: ellipsis;">Vendor_Card</div></div></th><th class="TableInteractive-headerCellData cellData text-brand-hover text-medium text-right"><div class="relative"><svg class="Icon Icon-chevronup Icon__StyledIcon-oj89wd-1 boNzPM" viewBox="0 0 32 32" width="8" height="8" fill="currentcolor" role="img" aria-label="chevronup icon" style="position: absolute; right: 100%; margin-right: 3px;"><path d="M1 20 L16 6 L31 20 L27 24 L16 14 L5 24 z"></path></svg><div class="" style="overflow: hidden; white-space: nowrap; text-overflow: ellipsis;">Spend_in_Period</div></div></th></tr></thead><tbody><tr data-testid="table-row"><td class="px1 border-bottom text-dark fullscreen-normal-text fullscreen-night-text text-bold" style="white-space: nowrap;"><span class="cellData inline-block cursor-pointer text-brand-hover"><img src="https://logo.clearbit.com/payemcard.com" style="height: 30px;"></span></td><td class="px1 border-bottom text-dark fullscreen-normal-text fullscreen-night-text text-bold" style="white-space: nowrap;"><span class="cellData inline-block cursor-pointer text-brand-hover"><div class="link link--wrappable">iDigital</div></span></td><td class="px1 border-bottom text-dark fullscreen-normal-text fullscreen-night-text text-bold text-right" style="white-space: nowrap;"><span class="cellData inline-block">152,055.63</span></td></tr><tr data-testid="table-row"><td class="px1 border-bottom text-dark fullscreen-normal-text fullscreen-night-text text-bold" style="white-space: nowrap;"><span class="cellData inline-block cursor-pointer text-brand-hover"><img src="https://logo.clearbit.com/google.com" style="height: 30px;"></span></td><td class="px1 border-bottom text-dark fullscreen-normal-text fullscreen-night-text text-bold" style="white-space: nowrap;"><span class="cellData inline-block cursor-pointer text-brand-hover"><div class="link link--wrappable">Google</div></span></td><td class="px1 border-bottom text-dark fullscreen-normal-text fullscreen-night-text text-bold text-right" style="white-space: nowrap;"><span class="cellData inline-block">96,204.45</span></td></tr><tr data-testid="table-row"><td class="px1 border-bottom text-dark fullscreen-normal-text fullscreen-night-text text-bold" style="white-space: nowrap;"><span class="cellData inline-block cursor-pointer text-brand-hover"><img src="https://logo.clearbit.com/payemcard.com" style="height: 30px;"></span></td><td class="px1 border-bottom text-dark fullscreen-normal-text fullscreen-night-text text-bold" style="white-space: nowrap;"><span class="cellData inline-block cursor-pointer text-brand-hover"><div class="link link--wrappable">g-plus</div></span></td><td class="px1 border-bottom text-dark fullscreen-normal-text fullscreen-night-text text-bold text-right" style="white-space: nowrap;"><span class="cellData inline-block">56,989.38</span></td></tr><tr data-testid="table-row"><td class="px1 border-bottom text-dark fullscreen-normal-text fullscreen-night-text text-bold" style="white-space: nowrap;"><span class="cellData inline-block cursor-pointer text-brand-hover"><img src="https://logo.clearbit.com/amazon.com" style="height: 30px;"></span></td><td class="px1 border-bottom text-dark fullscreen-normal-text fullscreen-night-text text-bold" style="white-space: nowrap;"><span class="cellData inline-block cursor-pointer text-brand-hover"><div class="link link--wrappable">Amazon</div></span></td><td class="px1 border-bottom text-dark fullscreen-normal-text fullscreen-night-text text-bold text-right" style="white-space: nowrap;"><span class="cellData inline-block">23,843.78</span></td></tr><tr data-testid="table-row"><td class="px1 border-bottom text-dark fullscreen-normal-text fullscreen-night-text text-bold" style="white-space: nowrap;"><span class="cellData inline-block cursor-pointer text-brand-hover"><img src="https://logo.clearbit.com/outreach.io" style="height: 30px;"></span></td><td class="px1 border-bottom text-dark fullscreen-normal-text fullscreen-night-text text-bold" style="white-space: nowrap;"><span class="cellData inline-block cursor-pointer text-brand-hover"><div class="link link--wrappable">Outreach</div></span></td><td class="px1 border-bottom text-dark fullscreen-normal-text fullscreen-night-text text-bold text-right" style="white-space: nowrap;"><span class="cellData inline-block">19,945.84</span></td></tr><tr data-testid="table-row"><td class="px1 border-bottom text-dark fullscreen-normal-text fullscreen-night-text text-bold" style="white-space: nowrap;"><span class="cellData inline-block cursor-pointer text-brand-hover"><img src="https://logo.clearbit.com/payemcard.com" style="height: 30px;"></span></td><td class="px1 border-bottom text-dark fullscreen-normal-text fullscreen-night-text text-bold" style="white-space: nowrap;"><span class="cellData inline-block cursor-pointer text-brand-hover"><div class="link link--wrappable">Bing</div></span></td><td class="px1 border-bottom text-dark fullscreen-normal-text fullscreen-night-text text-bold text-right" style="white-space: nowrap;"><span class="cellData inline-block">19,836.54</span></td></tr><tr data-testid="table-row"><td class="px1 border-bottom text-dark fullscreen-normal-text fullscreen-night-text text-bold" style="white-space: nowrap;"><span class="cellData inline-block cursor-pointer text-brand-hover"><img src="https://logo.clearbit.com/linkedin.com" style="height: 30px;"></span></td><td class="px1 border-bottom text-dark fullscreen-normal-text fullscreen-night-text text-bold" style="white-space: nowrap;"><span class="cellData inline-block cursor-pointer text-brand-hover"><div class="link link--wrappable">LinkedIn</div></span></td><td class="px1 border-bottom text-dark fullscreen-normal-text fullscreen-night-text text-bold text-right" style="white-space: nowrap;"><span class="cellData inline-block">17,737.31</span></td></tr><tr data-testid="table-row"><td class="px1 border-bottom text-dark fullscreen-normal-text fullscreen-night-text text-bold" style="white-space: nowrap;"><span class="cellData inline-block cursor-pointer text-brand-hover"><img src="https://logo.clearbit.com/demostack.com" style="height: 30px;"></span></td><td class="px1 border-bottom text-dark fullscreen-normal-text fullscreen-night-text text-bold" style="white-space: nowrap;"><span class="cellData inline-block cursor-pointer text-brand-hover"><div class="link link--wrappable">Demostack</div></span></td><td class="px1 border-bottom text-dark fullscreen-normal-text fullscreen-night-text text-bold text-right" style="white-space: nowrap;"><span class="cellData inline-block">16,440</span></td></tr><tr data-testid="table-row"><td class="px1 border-bottom text-dark fullscreen-normal-text fullscreen-night-text text-bold" style="white-space: nowrap;"><span class="cellData inline-block cursor-pointer text-brand-hover"><img src="https://logo.clearbit.com/netsuite.com" style="height: 30px;"></span></td><td class="px1 border-bottom text-dark fullscreen-normal-text fullscreen-night-text text-bold" style="white-space: nowrap;"><span class="cellData inline-block cursor-pointer text-brand-hover"><div class="link link--wrappable">NetSuite</div></span></td><td class="px1 border-bottom text-dark fullscreen-normal-text fullscreen-night-text text-bold text-right" style="white-space: nowrap;"><span class="cellData inline-block">14,243.63</span></td></tr><tr data-testid="table-row"><td class="px1 border-bottom text-dark fullscreen-normal-text fullscreen-night-text text-bold" style="white-space: nowrap;"><span class="cellData inline-block cursor-pointer text-brand-hover"><img src="https://logo.clearbit.com/payemcard.com" style="height: 30px;"></span></td><td class="px1 border-bottom text-dark fullscreen-normal-text fullscreen-night-text text-bold" style="white-space: nowrap;"><span class="cellData inline-block cursor-pointer text-brand-hover"><div class="link link--wrappable">SCHNIEDER COMPUTING </div></span></td><td class="px1 border-bottom text-dark fullscreen-normal-text fullscreen-night-text text-bold text-right" style="white-space: nowrap;"><span class="cellData inline-block">12,736.16</span></td></tr><tr data-testid="table-row"><td class="px1 border-bottom text-dark fullscreen-normal-text fullscreen-night-text text-bold" style="white-space: nowrap;"><span class="cellData inline-block cursor-pointer text-brand-hover"><img src="https://logo.clearbit.com/payemcard.com" style="height: 30px;"></span></td><td class="px1 border-bottom text-dark fullscreen-normal-text fullscreen-night-text text-bold" style="white-space: nowrap;"><span class="cellData inline-block cursor-pointer text-brand-hover"><div class="link link--wrappable">AWS</div></span></td><td class="px1 border-bottom text-dark fullscreen-normal-text fullscreen-night-text text-bold text-right" style="white-space: nowrap;"><span class="cellData inline-block">10,972.39</span></td></tr><tr data-testid="table-row"><td class="px1 border-bottom text-dark fullscreen-normal-text fullscreen-night-text text-bold" style="white-space: nowrap;"><span class="cellData inline-block cursor-pointer text-brand-hover"><img src="https://logo.clearbit.com/payemcard.com" style="height: 30px;"></span></td><td class="px1 border-bottom text-dark fullscreen-normal-text fullscreen-night-text text-bold" style="white-space: nowrap;"><span class="cellData inline-block cursor-pointer text-brand-hover"><div class="link link--wrappable">Ksp</div></span></td><td class="px1 border-bottom text-dark fullscreen-normal-text fullscreen-night-text text-bold text-right" style="white-space: nowrap;"><span class="cellData inline-block">10,691.85</span></td></tr></tbody></table></div></div><div class="p1 flex flex-no-shrink flex-align-right fullscreen-normal-text fullscreen-night-text"><span class="text-bold">Rows 1-12 of 22</span><span class="text-brand-hover px1 cursor-pointer disabled"><svg class="Icon Icon-triangle_left Icon__StyledIcon-oj89wd-1 boNzPM" viewBox="0 0 32 32" width="10" height="10" fill="currentcolor" role="img" aria-label="triangle_left icon"><path d="M21,0 L5,16 L21,32 L21,5.47117907e-13 L21,0 Z"></path></svg></span><span class="text-brand-hover pr1 cursor-pointer"><svg class="Icon Icon-triangle_right Icon__StyledIcon-oj89wd-1 boNzPM" viewBox="0 0 32 32" width="10" height="10" fill="currentcolor" role="img" aria-label="triangle_right icon"><path d="M9,0 L25,16 L9,32 L9,5.47117907e-13 L9,0 Z"></path></svg></span></div></div></div></div><span class="react-resizable-handle react-resizable-handle-se"></span></div>